### ISSUE TITLE
Problem with Example

### ISSUE THREAD

**Issue by dragonburn1991** [pankajkarman/bias_correction#2]
Hello, Thank you for sharing your bias correction programs

I am following the example from https://github.com/pankajkarman/bias_correction/blob/master/example.ipynb.
However, when I get some error when I try to bias correction by using this command: df2 = bc.correct(method='basic_quantile').

The error as followed:
ValueError                                Traceback (most recent call last)
<ipython-input-37-cfe3a9a481de> in <module>()
----> 1 df1 = bc.correct(method='basic_quantile')

~/anaconda3/lib/python3.7/site-packages/bias_correction.py in correct(self, method, lower_limit, cdf_threshold)
    136                                                       cdf_threshold=cdf_threshold)
    137         elif method == 'basic_quantile':
--> 138             corrected = quantile_correction(self.obs_data, self.mod_data, self.sce_data, modified = False)
    139         else:
    140             corrected = quantile_correction(self.obs_data, self.mod_data, self.sce_data, modified = True)

~/anaconda3/lib/python3.7/site-packages/bias_correction.py in quantile_correction(obs_data, mod_data, sce_data, modified)
     15 
     16 def quantile_correction(obs_data, mod_data, sce_data, modified = True):
---> 17     cdf = ECDF(mod_data)
     18     p = cdf(sce_data)
     19     cor = np.subtract(*[np.nanpercentile(x, p) for x in [obs_data, mod_data]])

~/anaconda3/lib/python3.7/site-packages/statsmodels/distributions/empirical_distribution.py in __init__(self, x, side)
    139             nobs = len(x)
    140             y = np.linspace(1./nobs,1,nobs)
--> 141             super(ECDF, self).__init__(x, y, side=side, sorted=True)
    142         else:
    143             return interp1d(x,y,drop_errors=False,fill_values=ival)

~/anaconda3/lib/python3.7/site-packages/statsmodels/distributions/empirical_distribution.py in __init__(self, x, y, ival, sorted, side)
     87         if _x.shape != _y.shape:
     88             msg = "x and y do not have the same shape"
---> 89             raise ValueError(msg)
     90         if len(_x.shape) != 1:
     91             msg = 'x and y must be 1-dimensional'

ValueError: x and y do not have the same shape

I was wondering how can I fix this issue.

Thank you in advance

**Comment by pankajkarman** [comment]
It seems you are using the pip version of the code. Please use the latest code on github. Pip code has a few issues which have been resolved. However, I have not pushed the latest version to pip as the normal correction for multi-dimensional data is still not working. Will push the code to pip once this issue is resolved.

Thanks

**Comment by drmshaltout** [comment]
Hello
 I would like to test the following command for only one station 
Could I use an excel file for the model, and data_to_be_corrected? and also for reference?
and what are the format of this excel file 
bc = BiasCorrection(reference, model, data_to_be_corrected)

**Comment by pankajkarman** [comment]
You could have a single excel file for model, reference and data_to_be_corrected or separate files for all these three. However, model and reference should have some overlap time period. In short, model and reference are datasets which you use to find bias and then this bias is used to correct the data_to_be_corrected.

**Comment by pankajkarman** [comment]
![ex](https://user-images.githubusercontent.com/34066356/107177749-95be1380-69f8-11eb-9d72-3f1f9e01a7df.png)
Take a look at the attached image for an example.

**Comment by drmshaltout** [comment]
Thanks for your answer
Could you please send me a sample for the following: MODEL_HISTORIQUE.txt; OBSERVED.txt; Model.txt;    To prepare my files to be like them.
All the best and Thank you in advance
Mohamed

**Comment by pankajkarman** [comment]
[MODEL.txt](https://github.com/pankajkarman/bias_correction/files/5963449/MODEL.txt)
[MODEL_HISTORIQUE.txt](https://github.com/pankajkarman/bias_correction/files/5963450/MODEL_HISTORIQUE.txt)
[OBSERVED.txt](https://github.com/pankajkarman/bias_correction/files/5963451/OBSERVED.txt)

Please find herewith attached example files requested. Hope It's useful.

Thanks

**Comment by pankajkarman** [comment]
[MODEL.txt](https://github.com/pankajkarman/bias_correction/files/5963473/MODEL.txt)
[MODEL_HISTORIQUE.txt](https://github.com/pankajkarman/bias_correction/files/5963474/MODEL_HISTORIQUE.txt)
[OBSERVED.txt](https://github.com/pankajkarman/bias_correction/files/5963476/OBSERVED.txt)

Here are the requested files. Hope it's useful.

Thanks

**Comment by drmshaltout** [comment]
Thank you for your prompt answer.

Please find the attached script that I used to bias-corrected the data that you send to me.

I get one simple error
     >>> ax.legand ()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'AxesSubplot' object has no attribute 'legand'

**and I get this error also, could you tell me how to fix it.**
bc = BiasCorrection(ref, mod, sce)
>>> corrected = bc.correct(method='gamma_mapping')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36-32\lib\site-packages\bias_correction.py", line 133, in correct
    cdf_threshold=cdf_threshold)
  File "C:\Python36-32\lib\site-packages\bias_correction.py", line 35, in gamma_correction
    obs_gamma, mod_gamma, sce_gamma = [gamma.fit(x) for x in [obs_raindays, mod_raindays, sce_raindays]]
  File "C:\Python36-32\lib\site-packages\bias_correction.py", line 35, in <listcomp>
    obs_gamma, mod_gamma, sce_gamma = [gamma.fit(x) for x in [obs_raindays, mod_raindays, sce_raindays]]
  File "C:\Python36-32\lib\site-packages\scipy\stats\_continuous_distns.py", line 2860, in fit
    return super(gamma_gen, self).fit(data, *args, **kwds)
  File "C:\Python36-32\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 2302, in fit
    if not np.isfinite(data).all():
  File "C:\Python36-32\lib\site-packages\pandas\core\generic.py", line 1330, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
![ERROR](https://user-images.githubusercontent.com/78708120/107631712-218ca580-6c6e-11eb-9135-4fe72dc86cf8.png)

**Comment by Levin000** [comment]
> Thank you for your prompt answer.
> 
> Please find the attached script that I used to bias-corrected the data that you send to me.
> 
> I get one simple error
> >>> ax.legand ()
> Traceback (most recent call last):
> File "", line 1, in
> AttributeError: 'AxesSubplot' object has no attribute 'legand'
> 
> **and I get this error also, could you tell me how to fix it.**
> bc = BiasCorrection(ref, mod, sce)
> 
> > > > corrected = bc.correct(method='gamma_mapping')
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "C:\Python36-32\lib\site-packages\bias_correction.py", line 133, in correct
> > > > cdf_threshold=cdf_threshold)
> > > > File "C:\Python36-32\lib\site-packages\bias_correction.py", line 35, in gamma_correction
> > > > obs_gamma, mod_gamma, sce_gamma = [gamma.fit(x) for x in [obs_raindays, mod_raindays, sce_raindays]]
> > > > File "C:\Python36-32\lib\site-packages\bias_correction.py", line 35, in 
> > > > obs_gamma, mod_gamma, sce_gamma = [gamma.fit(x) for x in [obs_raindays, mod_raindays, sce_raindays]]
> > > > File "C:\Python36-32\lib\site-packages\scipy\stats_continuous_distns.py", line 2860, in fit
> > > > return super(gamma_gen, self).fit(data, *args, **kwds)
> > > > File "C:\Python36-32\lib\site-packages\scipy\stats_distn_infrastructure.py", line 2302, in fit
> > > > if not np.isfinite(data).all():
> > > > File "C:\Python36-32\lib\site-packages\pandas\core\generic.py", line 1330, in **nonzero**
> > > > f"The truth value of a {type(self).**name**} is ambiguous. "
> > > > ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
> > > > ![ERROR](https://user-images.githubusercontent.com/78708120/107631712-218ca580-6c6e-11eb-9135-4fe72dc86cf8.png)

Are you mean ax.legend()?

**Comment by drmshaltout** [comment]
Yes this is one error about **ax.legend()**
and ther are another error related to ; **corrected = bc.correct(method='gamma_mapping')**
